-- ===========================================================================
-- AGnVET Trial Work — fresh project setup (generated by `npm run sql:fresh`,
-- do not edit: change server/migrations/ and regenerate).
--
-- Paste the WHOLE file into the new project's SQL editor and run once.
-- It is migrations 001 + 003 + 004 in order: full schema, RLS, seeds, and
-- the invite-only signup lockdown — the new project is never open.
--
-- >>> ONE EDIT BEFORE RUNNING: the INVITED PEOPLE block at the very end. <<<
--
-- Afterwards, in the dashboard (SQL cannot reach these):
--   1. Authentication -> Sign In / Up -> turn OFF "Allow new users to sign up".
--   2. (Optional) leave "Confirm email" off for a smoother first sign-in.
-- ===========================================================================

-- ────────────────── from server/migrations/001_init.sql ──────────────────

-- ===========================================================================
-- AGnVET Trial Work — initial migration (run ONCE in the Supabase SQL editor)
-- Creates the full schema, row-level security, the signup trigger, the photo
-- storage bucket, and seeds the org + the two 2026 sites/trials with the
-- fixed ids the apps reference (shared/supa.ts).
-- ===========================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Core tables

create table orgs (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now()
);

create table people (
  id          uuid primary key,
  org_id      uuid not null references orgs,
  name        text not null,
  email       text not null,
  role        text not null check (role in ('admin','agronomist','team','grower','rep')),
  created_at  timestamptz not null default now()
);

create table clients (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  name        text not null,
  contact     jsonb,
  created_at  timestamptz not null default now()
);

create table sites (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  client_id   uuid references clients,
  property    text not null,
  town        text,
  lat         double precision,
  lng         double precision,
  paddock     text,
  soil        text,
  ph          numeric,
  bearing     numeric,
  corners     jsonb,
  history     jsonb not null default '[]',
  created_at  timestamptz not null default now()
);

create table products (
  pcode       integer primary key,
  name        text not null,
  company     text not null,
  category    text not null,
  formulation text,
  schedule    text,
  actives     jsonb not null default '[]',
  updated_at  timestamptz not null default now()
);

create table experimental_products (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  name        text not null,
  company     text,
  category    text,
  actives     jsonb not null default '[]',
  notes       text,
  created_by  uuid references people,
  created_at  timestamptz not null default now()
);

create table protocols (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  name        text not null,
  crop        text,
  treatments  jsonb not null default '[]',
  assessments jsonb not null default '[]',
  created_by  uuid references people,
  created_at  timestamptz not null default now()
);

create table trial_groups (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  name        text not null,
  protocol_id uuid references protocols,
  created_at  timestamptz not null default now()
);

create table trials (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  client_id   uuid references clients,
  site_id     uuid references sites,
  group_id    uuid references trial_groups,
  protocol_id uuid references protocols,
  name        text not null,
  season      integer not null,
  status      text not null default 'draft'
              check (status in ('draft','review','approved','active','complete','archived')),
  trial_type  text not null default 'plot'
              check (trial_type in ('demonstration','plot','paddock_scale')),
  aim         text,
  crop        text,
  variety     text,
  sown_date   date,
  design      jsonb not null default '{}',
  layout      jsonb,
  spraying    jsonb,
  created_by  uuid references people,
  approved_by uuid references people,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table treatments (
  id          uuid primary key default gen_random_uuid(),
  trial_id    uuid not null references trials on delete cascade,
  n           integer not null,
  name        text not null,
  b_spray     boolean not null default false,
  components  jsonb not null default '[]',
  recipe      text,
  unique (trial_id, n)
);

create table assessments (
  id          uuid primary key default gen_random_uuid(),
  trial_id    uuid not null references trials on delete cascade,
  n           integer not null,
  timing      text,
  measures    jsonb not null default '[]',
  blind       boolean not null default false,
  unique (trial_id, n)
);

create table documents (
  id          uuid primary key default gen_random_uuid(),
  trial_id    uuid references trials on delete cascade,
  org_id      uuid not null references orgs,
  kind        text not null check (kind in ('spray-map','mixing-plan','arm-export','protocol','other')),
  filename    text not null,
  storage_path text not null,
  parsed      jsonb,
  uploaded_by uuid references people,
  created_at  timestamptz not null default now()
);

create table operations (
  id          uuid primary key default gen_random_uuid(),
  trial_id    uuid not null references trials on delete cascade,
  kind        text not null check (kind in ('sow','fertilise','spray')),
  timing      text,
  detail      jsonb not null default '{}',
  performed_at timestamptz,
  performed_by uuid references people,
  conditions  jsonb
);

create table fert_products (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  name        text not null,
  analysis    jsonb not null default '{}',
  form        text,
  notes       text
);

create table site_weather (
  site_id     uuid not null references sites on delete cascade,
  date        date not null,
  min_temp    numeric not null,
  max_temp    numeric not null,
  rain        numeric,
  source      text not null default 'silo',
  primary key (site_id, date)
);

create table phenology_calibrations (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references orgs,
  crop        text not null,
  variety     text not null,
  factor      numeric,
  stage_tt    jsonb,
  source      text,
  unique (org_id, crop, variety)
);

create table scores (
  id          uuid primary key,
  trial_id    uuid not null references trials on delete cascade,
  assessment  integer not null,
  plot        integer not null,
  measure     text not null,
  value       numeric,
  note        text,
  assessor    uuid references people,
  recorded_at timestamptz not null,
  synced_at   timestamptz not null default now()
);
create index scores_trial on scores (trial_id, assessment, plot);

create table photos (
  id          uuid primary key,
  trial_id    uuid not null references trials on delete cascade,
  plot        integer,
  storage_path text not null,
  taken_by    uuid references people,
  taken_at    timestamptz not null,
  meta        jsonb
);

create table corrections (
  id          uuid primary key,
  trial_id    uuid not null references trials on delete cascade,
  plot        integer not null,
  kind        text not null check (kind in ('relabel','exclude')),
  original_t  integer,
  effective_t integer,
  reason      text,
  made_by     uuid references people,
  made_at     timestamptz not null
);

create table sync_log (
  id          bigint generated always as identity primary key,
  org_id      uuid not null references orgs,
  device      text,
  person_id   uuid references people,
  pushed_at   timestamptz not null default now(),
  items       integer not null,
  payload     jsonb
);

-- ---------------------------------------------------------------------------
-- Signup → people row (everyone joins the AGnVET org as agronomist; adjust
-- roles later from the people table)

create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.people (id, org_id, name, email, role)
  values (
    new.id,
    '00000000-0000-0000-0000-000000000001',
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    'agronomist'
  )
  on conflict (id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row-level security

-- security definer: the people policy references this function; without
-- definer rights the lookup recurses through RLS.
create function current_org() returns uuid
language sql stable security definer set search_path = public as
  $$ select org_id from public.people where id = auth.uid() $$;

alter table orgs enable row level security;
create policy orgs_read on orgs for select using (id = current_org());

alter table people enable row level security;
create policy people_read on people for select using (org_id = current_org());

alter table products enable row level security;
create policy products_public_read on products for select using (true);

-- org-scoped tables: full access within your org
do $$
declare t text;
begin
  foreach t in array array['clients','sites','experimental_products','protocols','trial_groups','trials','documents','fert_products','phenology_calibrations','sync_log']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy %I_org_all on %I for all using (org_id = current_org()) with check (org_id = current_org())', t, t);
  end loop;
end $$;

-- trial-scoped tables: access follows the trial's org
do $$
declare t text;
begin
  foreach t in array array['treatments','assessments','operations','scores','photos','corrections']
  loop
    execute format('alter table %I enable row level security', t);
    execute format(
      'create policy %I_trial_all on %I for all using (trial_id in (select id from trials where org_id = current_org())) with check (trial_id in (select id from trials where org_id = current_org()))',
      t, t);
  end loop;
end $$;

alter table site_weather enable row level security;
create policy site_weather_all on site_weather for all
  using (site_id in (select id from sites where org_id = current_org()))
  with check (site_id in (select id from sites where org_id = current_org()));

-- ---------------------------------------------------------------------------
-- Photo storage bucket

insert into storage.buckets (id, name, public) values ('photos', 'photos', false)
on conflict (id) do nothing;

create policy photos_bucket_rw on storage.objects for all to authenticated
  using (bucket_id = 'photos') with check (bucket_id = 'photos');

-- ---------------------------------------------------------------------------
-- Seed: org, sites, trials (fixed ids referenced by shared/supa.ts)

insert into orgs (id, name)
values ('00000000-0000-0000-0000-000000000001', 'AGnVET Services — IK Caldwell')
on conflict (id) do nothing;

insert into sites (id, org_id, property, town, lat, lng, paddock, soil)
values
  ('00000000-0000-0000-0000-000000000011', '00000000-0000-0000-0000-000000000001',
   '‘Glenview’', 'Matong NSW', -34.768, 146.929, 'Church block', 'red-brown earth'),
  ('00000000-0000-0000-0000-000000000012', '00000000-0000-0000-0000-000000000001',
   '‘Hillview’', 'Ganmain NSW', -34.792, 147.041, 'Racecourse block', 'pH 5.4 (CaCl2)')
on conflict (id) do nothing;

insert into trials (id, org_id, site_id, name, season, status, trial_type, crop, variety, sown_date, aim)
values
  ('00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000001',
   '00000000-0000-0000-0000-000000000011', 'Matong Wheat Fungicide Demo 2026', 2026, 'active',
   'demonstration', 'Wheat', 'Scepter', '2026-05-12',
   'Compare label-rate foliar fungicide programs for stripe rust and septoria in Scepter wheat, and show the timing response (GS31 vs GS39) at the Matong field day.'),
  ('00000000-0000-0000-0000-000000000102', '00000000-0000-0000-0000-000000000001',
   '00000000-0000-0000-0000-000000000012', 'Ganmain Barley Net Blotch 2026', 2026, 'review',
   'plot', 'Barley', 'Spartacus CL', '2026-05-08',
   'Compare registered foliar fungicides and one experimental SDHI for net form net blotch in Spartacus CL barley.')
on conflict (id) do nothing;


-- ────────────────── from server/migrations/003_ringwood.sql ──────────────────

-- ===========================================================================
-- Seed: Ringwood (Corowa) wheat fungicide trial 2026 — site + trial with the
-- fixed ids the apps reference (shared/supa.ts). Idempotent; safe to re-run.
-- The field app can also self-seed these rows through RLS, so this migration
-- is a fallback — run it once in the SQL editor if the rows aren't there.
-- ===========================================================================

insert into sites (id, org_id, property, town, lat, lng, paddock, soil)
values
  ('00000000-0000-0000-0000-000000000013', '00000000-0000-0000-0000-000000000001',
   '‘Ringwood’', 'Corowa NSW', -35.99, 146.39, null, null)
on conflict (id) do nothing;

insert into trials (id, org_id, site_id, name, season, status, trial_type, crop, sown_date, aim)
values
  ('00000000-0000-0000-0000-000000000103', '00000000-0000-0000-0000-000000000001',
   '00000000-0000-0000-0000-000000000013', 'Ringwood (Corowa) — Wheat Fungicide 2026', 2026, 'active',
   'plot', 'Wheat', null,
   'Sequential A+B foliar fungicide comparison in wheat: 24 treatments × 3 reps RCB, registered standards plus experimental actives (G295, Vimoy Iblon, CUF37) against the Soprano 500 base program.')
on conflict (id) do nothing;

-- Verification: expect 3 sites, 3 trials
select (select count(*) from sites) as sites, (select count(*) from trials) as trials;


-- ────────────────── from server/migrations/004_close_open_signup.sql ──────────────────

-- ===========================================================================
-- 004 — Close open signup, scope the photo bucket, least-privilege roles
--
--   *** PREPARED, NOT YET APPLIED. Read docs/HOSTING-BRIEF.md first. ***
--
-- What 001 does today, and why it has to change before anyone else touches
-- the project:
--
--   * `handle_new_user()` puts EVERY new auth user into the AGnVET org as
--     `agronomist`. Email signup is on with autoconfirm, so anyone who finds
--     the project URL + publishable key (both public, in the deployed JS
--     bundle) can create an account and read/write every trial, site, client,
--     score and photo record in the org. RLS is working exactly as written —
--     the problem is that the front door lets anyone become an org member.
--   * `photos_bucket_rw` grants any authenticated user full access to the
--     whole bucket with no org scoping.
--
-- This migration replaces both with invite-only provisioning and an
-- org-partitioned bucket. Run it in the Supabase SQL editor, then ALSO turn
-- OFF Authentication → Sign In / Up → "Allow new users to sign up" in the
-- dashboard: the trigger is defence in depth, the dashboard toggle is the
-- actual front door.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Who is allowed in, and as what

create table if not exists allowed_signups (
  email       text primary key,
  org_id      uuid not null references orgs,
  role        text not null default 'team' check (role in ('admin','agronomist','team','grower','rep')),
  invited_by  text,
  invited_at  timestamptz not null default now(),
  claimed_at  timestamptz
);

alter table allowed_signups enable row level security;

-- Only admins of the org can see or manage invitations.
drop policy if exists allowed_signups_admin on allowed_signups;
create policy allowed_signups_admin on allowed_signups for all
  using (org_id = current_org()
         and exists (select 1 from people p where p.id = auth.uid() and p.role = 'admin'))
  with check (org_id = current_org()
         and exists (select 1 from people p where p.id = auth.uid() and p.role = 'admin'));

-- Seed the invitations you actually want. Add one row per real person —
-- replace these with the pilot list before running.
--
-- insert into allowed_signups (email, org_id, role, invited_by) values
--   ('andrew.rolfe@agnvet.com.au', '00000000-0000-0000-0000-000000000001', 'admin',      'setup'),
--   ('someone.else@agnvet.com.au', '00000000-0000-0000-0000-000000000001', 'agronomist', 'setup')
-- on conflict (email) do nothing;

-- ---------------------------------------------------------------------------
-- 2. Signup trigger: invited addresses only, role from the invitation
--
-- An uninvited signup no longer becomes an org member. The auth user is
-- still created (Auth owns that table), but with no `people` row
-- current_org() returns null and every RLS policy denies — they see nothing.

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare inv allowed_signups%rowtype;
begin
  select * into inv from public.allowed_signups
   where lower(email) = lower(new.email);

  if not found then
    -- Uninvited: no org membership, therefore no data access.
    return new;
  end if;

  insert into public.people (id, org_id, name, email, role)
  values (
    new.id,
    inv.org_id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    inv.role
  )
  on conflict (id) do nothing;

  update public.allowed_signups set claimed_at = now() where email = inv.email;
  return new;
end $$;

-- ---------------------------------------------------------------------------
-- 3. Retro-check: who is already in the org?
--
-- 001 has been live with open signup, so review the existing membership and
-- remove anyone who should not be there. Run this SELECT first, then delete.
--
--   select id, email, role, created_at from people order by created_at;
--   delete from people where email not in (select email from allowed_signups);
--
-- Deleting the `people` row revokes all data access. Also delete the matching
-- auth user (Authentication → Users) so the login itself stops working.

-- ---------------------------------------------------------------------------
-- 4. Photo bucket: partition by org, not "any authenticated user"
--
-- Object paths become `{org_id}/{trial_id}/{photo_id}.jpg` (see
-- src/lib/backend.ts). The first path segment is the org, so the policy can
-- scope on it. No blobs have been uploaded yet, so there is nothing to move.

drop policy if exists photos_bucket_rw on storage.objects;

create policy photos_bucket_org_read on storage.objects for select to authenticated
  using (bucket_id = 'photos' and (storage.foldername(name))[1] = current_org()::text);

create policy photos_bucket_org_write on storage.objects for insert to authenticated
  with check (bucket_id = 'photos' and (storage.foldername(name))[1] = current_org()::text);

create policy photos_bucket_org_update on storage.objects for update to authenticated
  using (bucket_id = 'photos' and (storage.foldername(name))[1] = current_org()::text)
  with check (bucket_id = 'photos' and (storage.foldername(name))[1] = current_org()::text);

-- Deliberately no delete policy: field photos are trial evidence. Removal is
-- an admin action through the dashboard, not something a phone can do.

-- ===========================================================================
-- INVITED PEOPLE — >>> EDIT THIS LIST, THEN RUN <<<
--
-- One row per person allowed to sign in. Roles: admin | agronomist | team |
-- grower | rep. Anyone not listed here cannot become an org member even if
-- they somehow create an auth account.
-- ===========================================================================

insert into allowed_signups (email, org_id, role, invited_by) values
  ('andrew.rolfe@agnvet.com.au', '00000000-0000-0000-0000-000000000001', 'admin', 'setup')
  -- , ('colleague@agnvet.com.au', '00000000-0000-0000-0000-000000000001', 'agronomist', 'setup')
on conflict (email) do nothing;

select email, role from allowed_signups order by email;
