#!/usr/bin/env node
/**
 * Vendor the two brand webfonts locally — `npm run fonts:build`.
 *
 * The apps used to pull Mulish and IBM Plex Mono from fonts.googleapis.com on
 * every page load. Two reasons that had to change:
 *
 *   1. Offline-first. The field app is meant to work with no signal, but a
 *      first load in a paddock had to reach Google before text rendered in the
 *      brand faces — until the font cache filled, everything fell back to
 *      Arial. Self-hosted fonts are picked up by the service worker with the
 *      rest of the app shell.
 *   2. It was the only avoidable third-party request at runtime, and so the
 *      only avoidable row in the dependency register IT will ask for.
 *
 * Both faces are SIL Open Font License 1.1 — redistribution is permitted, and
 * the licence text ships beside the files in each public/fonts directory.
 *
 * Mulish is a variable font, so one file covers 400–900. IBM Plex Mono is not,
 * so it needs one file per weight the apps actually use (400/500/600/700 —
 * grep for `${MONO}` before trimming this list).
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

// The two apps are built independently by separate Vite configs, each with its
// own publicDir, so the files are written into both rather than shared.
const TARGETS = ['public/fonts', 'portal/public/fonts']

const FAMILIES = [
  { css: 'Mulish:wght@400..900', slug: 'mulish' },
  { css: 'IBM+Plex+Mono:wght@400;500;600;700', slug: 'plex-mono' },
]

// Latin only. Google serves cyrillic/greek/vietnamese subsets too; none of the
// content is in those scripts, and each one is another file to cache.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])

// Google returns woff2 @font-face blocks only for browser user-agents.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const LICENCE = `These fonts are redistributed under the SIL Open Font License, Version 1.1.

  Mulish          — Copyright (c) The Mulish Project Authors
                    https://github.com/googlefonts/mulish
  IBM Plex Mono   — Copyright (c) 2017 IBM Corp.
                    https://github.com/IBM/plex

Full licence text: https://openfontlicense.org/

Regenerate with \`npm run fonts:build\` (shared/fonts/build-fonts.mjs).
Do not edit these files by hand.
`

/** Pull one family's CSS and return its latin @font-face blocks, parsed. */
async function fetchFaces({ css, slug }) {
  const r = await fetch(`https://fonts.googleapis.com/css2?family=${css}&display=swap`, {
    headers: { 'User-Agent': UA },
  })
  if (!r.ok) throw new Error(`${slug}: Google Fonts returned ${r.status}`)
  const sheet = await r.text()

  const faces = []
  // Each block is preceded by a /* subset */ comment naming the subset.
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g
  for (const [, subset, block] of sheet.matchAll(re)) {
    if (!KEEP_SUBSETS.has(subset)) continue
    const pick = (prop) => block.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim()
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
    const weight = pick('font-weight')
    if (!url || !weight) continue
    faces.push({
      family: pick('font-family').replace(/['"]/g, ''),
      weight,
      unicodeRange: pick('unicode-range'),
      file: `${slug}-${weight.replace(/\s+/g, '-')}-${subset}.woff2`,
      url,
    })
  }
  if (!faces.length) throw new Error(`${slug}: no latin faces found — did the CSS format change?`)
  return faces
}

async function main() {
  const faces = (await Promise.all(FAMILIES.map(fetchFaces))).flat()

  const files = await Promise.all(
    faces.map(async (f) => {
      const r = await fetch(f.url, { headers: { 'User-Agent': UA } })
      if (!r.ok) throw new Error(`${f.file}: download returned ${r.status}`)
      return { name: f.file, bytes: Buffer.from(await r.arrayBuffer()) }
    }),
  )

  const stylesheet =
    `/* Generated by shared/fonts/build-fonts.mjs — do not edit.\n` +
    `   Self-hosted so the apps render in brand faces with no network. */\n\n` +
    faces
      .map((f) =>
        [
          '@font-face {',
          `  font-family: '${f.family}';`,
          '  font-style: normal;',
          `  font-weight: ${f.weight};`,
          '  font-display: swap;',
          `  src: url('./${f.file}') format('woff2');`,
          `  unicode-range: ${f.unicodeRange};`,
          '}',
        ].join('\n'),
      )
      .join('\n\n') + '\n'

  for (const dir of TARGETS) {
    await mkdir(dir, { recursive: true })
    await Promise.all(files.map((f) => writeFile(join(dir, f.name), f.bytes)))
    await writeFile(join(dir, 'fonts.css'), stylesheet)
    await writeFile(join(dir, 'OFL.txt'), LICENCE)
  }

  const total = files.reduce((n, f) => n + f.bytes.length, 0)
  for (const f of files) console.log(`  ${f.name.padEnd(38)} ${(f.bytes.length / 1024).toFixed(1)} KB`)
  console.log(`\n${files.length} files · ${(total / 1024).toFixed(1)} KB → ${TARGETS.join(', ')}`)
}

await main()
